---

# This Playbook prints Hello World

- hosts: all
  gather_facts: False
  become: no
  become_method: sudo
  remote_user: "{{ admin_username }}"

  tasks:      
    - name: Whoami
      raw: ls /
      register: output

    - name: Display username
      debug:
        msg: "{{ output }}"
