---

# This Playbook prints Hello World

- hosts: all
  gather_facts: False
  become: no
  become_method: sudo
  remote_user: "{{ admin_username }}"

  tasks:      
    - name: DISPLAY THE INJECTED EXTRA VAR
      debug:
        var: secret_key
        
    - name: DISPLAY THE INJECTED EXTRA VAR
      raw: "cat {{ secret_key }}"
  
    - name: Whoami
      raw: id
      register: whoami_on_host

    - name: Display username
      debug:
        msg: "{{ whoami_on_host }}"
